#!/usr/bin/env bash
# This script install and configure haproxy
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s '
frontend http
        bind *:80
        mode http
        default_backend web-backend       
backend web-backend
        balance roundrobin
        server 4815-web-01 54.146.239.63:80 check 
        server 4815-web-02 18.207.96.192:80 check 

' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
