#!/usr/bin/env bash
# script to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/local/var/www/html/index.html
sudo systemctl start nginx.service
 