#!/usr/bin/env bash
#redirecting it to a permanent page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-enabled/default
sudo systemctl start nginx.service
